################################################################
#
#
# Pipeline pipeline_cat_fastq.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

chromhmm:
    segment_bed: "/ifs/research-groups/botnar/proj003/analyses/Adam_analysis/Chromhmm/output.dir/JMJD3_J4_10_segments.bed"
