################################################################
#
# Pipeline pipeline_trna.py configuration file
#
# This pipeline.yml file lists some configuration options that you
# need to set before running the pipeline. 
#
################################################################

# Location of the cribbslab directory
cribbslab: '/ifs/projects/adam/cribbslab/'

# Project name
projectname: proj001

# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2018)

##########################################################
# UCSC database options
##########################################################

ucsc:
# UCSC database host
    host: genome-mysql.cse.ucsc.edu

# UCSC database user name
    user: genome

# UCSC database name
    database: hg19

# repeats to collect as ',' separated list
    repeattypes: DNA,LINE,SINE,LTR,Transposon

# RNA repeats to collect as ',' separated list
    rnatypes: RNA,rRNA,scRNA,snRNA,srpRNA,tRNA

# comma separated list of regular expressions (a word contained in the contig that defines the contigs to be removed) 
# for contigs (ensembl nomenclature)
# to be removed from ensembl_filename_gtf during genome
# sanitization
    remove_contigs: random,chrUn,na,alt


########################################################
# the genome to use (UCSC convention)
########################################################

genome: hg19





##########################################################
# 
##########################################################

###########################################################
# 
###########################################################
